version: '3.5'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      db_net:
        ipv4_address: 10.5.3.2
networks:
  db_net:
    ipam:
      driver: default
      config:
        - subnet: 10.5.3.0/16